services:
  - type: web
    name: Water
    env: static
    staticPublishPath: ./water/
  - type: web
    name: Whale
    env: static
    staticPublishPath: ./whale/
  - type: web
    name: Boat
    env: static
    staticPublishPath: ./boat/
  - type: web
    name: Boat2
    env: static
    staticPublishPath: ./boat/
  - type: web
    name: Boat3
    env: static
    staticPublishPath_typo: ./boat/
